### ISSUE TITLE
QR Code in README.md under "Support my projects" for bitcoin not scannable

### ISSUE THREAD

**Issue by Mohammed-Shoaib01** [IonicaBizau/imgpx#12]
The QR code under "Support my projects" in the README.md file is not scannable.

Looks like this is what you want the QR code for: ”bitcoin:1P9BRsmazNQcuyTxEqveUsnf5CERdq35V6”

But the QR code is not scannable.

**Comment by IonicaBizau** [comment]
Works for me...
